### ISSUE TITLE
Dispatcher SDK validator

### ISSUE THREAD

**Issue by bdhoine** [adobe/aemanalyser-maven-plugin#123]
Currently on AEM components are in scope but the AEM archetype also generates dispatcher configuration.
Are there also plans to include dispatcher validation?

**Comment by cziegeler** [comment]
At the moment we don't have plans to integrate dispatcher validation; for now we leave it to the dispatcher tools: https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/implementing/content-delivery/disp-overview.html?lang=en

**Comment by bdhoine** [comment]
Ok, that's unfortunate. Then we need to build our own plugin to take care of this. Thanks for the reply

**Comment by cziegeler** [comment]
@bdhoine Just curious, why do you want to build your own plugin? Do the provided tools not work for you?

**Comment by bdhoine** [comment]
The dispatcher sdk works but we are looking for a convenient way to validate our dispatcher config at maven build time. And seeing as the dispatcher validator is not available as a public artifact we will need to push this regularly and use the dependencies and exec plugin (or a custom one for convenience) to handle the download and execution. 

Another thing we need to test is to see if the dispatcher sdk can be run in cloud manager because it uses a container to run httpd to test the config and I'm not sure that the docker command can be used there. If not we need to create a flow to integrate this with other CI/CD tools and glueing it together with adobe.io events and webhooks. 

So a lot of custom setup just to have a validation of httpd/dispatcher static config files that I was hoping that would be available already 😅

**Comment by cziegeler** [comment]
Thanks @bdhoine - I understand, I can't promise anything but I'll pass this feedback on to the product team

**Comment by kwin** [comment]
> The dispatcher sdk works but we are looking for a convenient way to validate our dispatcher config at maven build time.

Look at https://github.com/adobe/aem-project-archetype/issues/564 for an alternative approach. I would rather have dedicated tools for dispatcher and AEM but indeed that requires the Dispatcher Validator in a dedicated Maven repository.
