### ISSUE TITLE
Precompiled scripts throw warning

### ISSUE THREAD

**Issue by royteeuwen** [adobe/aemanalyser-maven-plugin#124]
I have created an aem project based on archetype 33 with option to use precompiled scripts. Without any modification to the project, the following warnings are thrown:

```
[WARNING] [requirements-capabilities] com.mysite:aem-archetype-33-example.ui.apps:jar:precompiled-scripts:1.0.0-SNAPSHOT: Artifact com.mysite:aem-archetype-33-example.ui.apps:jar:precompiled-scripts:1.0.0-SNAPSHOT requires [com.mysite.aem-archetype-33-example.ui.apps.precompiled-scripts/1.0.0.SNAPSHOT] sling.servlet; filter:="(&(!(sling.servlet.selectors=*))(sling.servlet.resourceTypes=core/wcm/components/container/v1/container/new))"; resolution:=optional in start level 21 but while the requirement is optional no artifact is providing a matching capability in this start level. (com.mysite:aem-archetype-33-example.all:1.0.0-SNAPSHOT)
[WARNING] [requirements-capabilities] com.mysite:aem-archetype-33-example.ui.apps:jar:precompiled-scripts:1.0.0-SNAPSHOT: Artifact com.mysite:aem-archetype-33-example.ui.apps:jar:precompiled-scripts:1.0.0-SNAPSHOT requires [com.mysite.aem-archetype-33-example.ui.apps.precompiled-scripts/1.0.0.SNAPSHOT] sling.servlet; filter:="(&(!(sling.servlet.selectors=*))(sling.servlet.resourceTypes=core/fd/components/aemform/v1/aemform))"; resolution:=optional in start level 21 but while the requirement is optional no artifact is providing a matching capability in this start level. (com.mysite:aem-archetype-33-example.all:1.0.0-SNAPSHOT)
[WARNING] [requirements-capabilities] com.mysite:aem-archetype-33-example.ui.apps:jar:precompiled-scripts:1.0.0-SNAPSHOT: Artifact com.mysite:aem-archetype-33-example.ui.apps:jar:precompiled-scripts:1.0.0-SNAPSHOT requires [com.mysite.aem-archetype-33-example.ui.apps.precompiled-scripts/1.0.0.SNAPSHOT] sling.servlet; filter:="(&(!(sling.servlet.selectors=*))(sling.servlet.resourceTypes=core/wcm/components/form/container/v2/container/new))"; resolution:=optional in start level 21 but while the requirement is optional no artifact is providing a matching capability in this start level. (com.mysite:aem-archetype-33-example.all:1.0.0-SNAPSHOT)
```

I would expect there to be no warnings using the latest aem analyser + sdk so that I can set the mode to strictValidation

**Comment by kwin** [comment]
see #87. According to @cziegeler this should no longer be an issue with the newest API SDK

**Comment by royteeuwen** [comment]
@kwin  I just generated this project last week friday using the archetype and seeing as the archetype doesn't specify an sdk version, it should automatically use the latest.

I can also see that mentioned:

```
[INFO] Using detected SDK Version for analysis: com.adobe.aem:aem-sdk-api:2021.12.6151.20211217T120950Z-211100
```

**Comment by kwin** [comment]
Please check the exported capabilities from bundle `com.day.cq:cq-quickstart:jar:precompiled-scripts:2021.12.6151.20211217T120950Z-211100` listed in https://repo1.maven.org/maven2/com/adobe/aem/aem-sdk-api/2021.12.6151.20211217T120950Z-211100/aem-sdk-api-2021.12.6151.20211217T120950Z-211100-aem-publish-sdk.slingosgifeature

Seems that those resourceTypes are not provided (for whatever reason).

**Comment by royteeuwen** [comment]
OK so where should this bug persist? should it stay here ?

**Comment by kwin** [comment]
Most probably here is fine (alternatively at https://github.com/adobe/aem-project-archetype/issues) but probably adding some more details will probably help speeding up the processing of this issue.

**Comment by cziegeler** [comment]
I don't think that this is the same as #87. It rather sounds a problem with the requirements (or capabilities)

**Comment by royteeuwen** [comment]
OK, guess it's something you can fix on your end then @cziegeler  ;) ?

**Comment by cziegeler** [comment]
@royteeuwen Yes, we'll look into it
