### ISSUE TITLE
Split up api-regions-exportsimports in multiple tasks

### ISSUE THREAD

**Issue by royteeuwen** [adobe/aemanalyser-maven-plugin#130]
I am getting warnings from the aemanalyser plugin about importing packages without a version range. Sadly enough those warnings are coming from third party packages / bundles, over which we do not have the control.

To alleviate this, I would like to ignore the "importing packages without a version range", but it seems this is contained in the [api-regions-exportsimports](https://github.com/apache/sling-org-apache-sling-feature-extension-apiregions/blob/master/README.md#feature-model-analysers) task, which also checks if you are importing packages that are not visible in your specific region (being the global region). Would it be viable to split up this api-regions-exportsimports into multiple tasks? One for region visibility and one for version range imports (or other specific tasks that I am not aware of)

**Comment by royteeuwen** [comment]
Created Sling JIRA ticket and PR: 
https://issues.apache.org/jira/browse/SLING-11068
https://github.com/apache/sling-org-apache-sling-feature-extension-apiregions/pull/17

**Comment by cziegeler** [comment]
Thanks. I've moved one part of the analyser to Apache Sling Feature Analyser as that check is generic (independent from regions) and that module did have the same code already anyway.
With that we need new releases of Apache Sling Feature Analyser and Feature Extension Api Regions

**Comment by royteeuwen** [comment]
Super, thanks for the follow up!
