### ISSUE TITLE
Use EXTRACT_AND_REMOVE instead of KEEP for sling initial content policy

### ISSUE THREAD

**Issue by niekraaijmakers** [adobe/aemanalyser-maven-plugin#172]
### Expected Behaviour

The resulting packages and feature models need to be in line with the currently used build image process.
As we perform EXTRACT_AND_REMOVE internally and designate the mutable content to a separate folder, we should do the same in here.

The reason we extract the sling initial content is so that we can install the mutable content separately in the install mutable content deployment step.

### Actual Behaviour

Currently the sling initial content policy is set to KEEP. This results the sling initial content to be kept in the origin packages instead of being put in a separate one.

**Comment by cziegeler** [comment]
@niekraaijmakers I assume this issue can be closed?
