### ISSUE TITLE
Add a maven mojo to validate OSGi configurations

### ISSUE THREAD

**Issue by cziegeler** [adobe/aemanalyser-maven-plugin#178]
When you just want to validate your OSGi configurations, this currently requires multiple steps: usually building the project with the OSGi configurations, building the all package and running the aemanalyser-maven-plugin on that result. The plugin in turn then unpacks all content packages and eventually validates the OSGi configurations.
We could provide a mojo which just validates the OSGi configurations in the source without requiring all the extra steps.

**Comment by kwin** [comment]
Wouldn’t it make sense to implement this as Filevault validator (https://jackrabbit.apache.org/filevault/validation.html). That reduces the overhead during regular builds, allows for m2e support and can still be leveraged from the aem analyzer plugin.

**Comment by cziegeler** [comment]
Thats a valid option and can be done in addition. The benefit here is that the validation takes place before the content package is even built. I don't think that there is a significant overhead, but the feedback happens must faster.
m2e support can be added

**Comment by kwin** [comment]
>  before the content package is even built

That depends on the perspective. Currently end users must provide OSGi configurations in form of content packages as native feature model support is not provided by AEM.
