### ISSUE TITLE
Enable the repoinit analyser by default

### ISSUE THREAD

**Issue by rombert** [adobe/aemanalyser-maven-plugin#18]
### Expected Behaviour

Enable repoinit checks if the plug-in is not configured explicitly.  The repoinit plug-in is quick, does nothing if no repoinit extensions are present and is very useful. We should enable it by default.

### Actual Behaviour

Repoinit checks are not activated.

### Reproduce Scenario (including but not limited to)

Not applicable.

#### Steps to Reproduce

Not applicable.

#### Platform and Version

Not applicable.

#### Sample Code that illustrates the problem

Not applicable.

#### Logs taken while reproducing problem

Not applicable.

**Comment by kwin** [comment]
Hasn't this been resolved in 0.0.18?

**Comment by kwin** [comment]
Can we reenable the analyser (https://github.com/adobe/aemanalyser-maven-plugin/blob/4e1a129dc1f7853651e4fc765c32f2146cf8b50f/aemanalyser-maven-plugin/src/main/java/com/adobe/aem/analyser/AemAnalyser.java#L44) now that SLING-10215 is supposably fixed?
