### ISSUE TITLE
How to specify artifact override rule

### ISSUE THREAD

**Issue by royteeuwen** [adobe/aemanalyser-maven-plugin#196]
I am building an 'all' package that contains another package which has some of the same dependencies of different versions. When compiling the all package, I get the following exception:

[ERROR] Failed to execute goal com.adobe.aem:aemanalyser-maven-plugin:1.5.8:project-analyse (aem-analyser) on project daikin-aem-cloud.all: Execution aem-analyser of goal com.adobe.aem:aemanalyser-maven-plugin:1.5.8:project-analyse failed: Artifact override rule required to select between these two artifacts Artifact [id=io.wcm:io.wcm.caconfig.editor:jar:bundle:1.15.2] and Artifact [id=io.wcm:io.wcm.caconfig.editor:jar:bundle:1.12.2]. The rule must be specified for [io.wcm:io.wcm.caconfig.editor:jar:bundle:1.15.2] -> [Help 1]

How and where should I specify this artifact override rule?

**Comment by cziegeler** [comment]
Is this still a problem? It would be good to have a reproducible test case

**Comment by royteeuwen** [comment]
@cziegeler  this seems to be fixed when upgrading from 1.5.8 to 1.6.0 of the aemanalyser-maven-plugin!

Just for reference, I included a test project:

[aemanalyser-issue.zip](https://github.com/user-attachments/files/17072938/aemanalyser-issue.zip)

**Comment by cziegeler** [comment]
Thanks, will close this then
