### ISSUE TITLE
Maintain releases in GitHub

### ISSUE THREAD

**Issue by kwin** [adobe/aemanalyser-maven-plugin#20]
It would be nice to maintain all releases also in GitHub: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/managing-releases-in-a-repository so that one gets a quick overview of the history of releases and the last release version

**Comment by bosschaert** [comment]
Releases are currently all in Maven Central here: https://repo1.maven.org/maven2/com/adobe/aem/aemanalyser-maven-plugin/

**Comment by cziegeler** [comment]
releases are visible at https://github.com/adobe/aemanalyser-maven-plugin/releases

**Comment by cziegeler** [comment]
Added the missing releases

**Comment by kwin** [comment]
And again: New releases don't show up

**Comment by bosschaert** [comment]
@kwin are you aware of a way to automate this?

**Comment by kwin** [comment]
https://github.com/marketplace?type=actions&query=github+releases
