### ISSUE TITLE
Add link to Adobe documentation

### ISSUE THREAD

**Issue by kwin** [adobe/aemanalyser-maven-plugin#218]
A link to https://experienceleague.adobe.com/en/docs/experience-manager-core-components/using/developing/archetype/build-analyzer-maven-plugin would be helpful to have in the README for the maven plugin (https://github.com/adobe/aemanalyser-maven-plugin/blob/main/aemanalyser-maven-plugin/README.md)

**Comment by cziegeler** [comment]
it is there https://github.com/adobe/aemanalyser-maven-plugin/blob/main/aemanalyser-maven-plugin/README.md?plain=1#L162
