### ISSUE TITLE
Environment specific OSGi bundles are rejected while environment specific OSGi configuration are not

### ISSUE THREAD

**Issue by kwin** [adobe/aemanalyser-maven-plugin#27]
A package containing an OSGi bundle below `/apps/myapp/install.author.dev` is rejected while a package containing an OSGi configuration below `/apps/myapp/config.author.dev` is accepted.
This is due to the fact that the `filterPatterns` are set in https://github.com/adobe/aemanalyser-maven-plugin/blob/cff01c57dee307d933ca8fbb45015cd6b5f7d9ca/aemanalyser-maven-plugin/src/main/java/com/adobe/aem/analyser/mojos/ConvertToFeatureModelMojo.java#L61.

IMHO both configurations and bundles should be treated the same, because both are first party citizens of a feature model.
Also multiple run modes lead correctly to different feature models.

I can only imagine that multiple run modes are a problem for embedded subpackages, as they are not as separate as OSGi bundles and configurations.

**Comment by kwin** [comment]
I think content packages are restricted to not depend on the environment run mode because the same docker image is used for both STAGE and PROD. Only author and publish is always completely separated. For OSGi configurations and bundles it should be no problem to depend on the environment because these changes don't change the immutable part of the repo (part of the docker image).

**Comment by cziegeler** [comment]
Environment specific OSGi bundles are not allowed in AEM Cloud Service

**Comment by kwin** [comment]
Thanks for the response @cziegeler. Could you give some reasoning?

**Comment by cziegeler** [comment]
The same code should be deployed in the environments - it would be dangerous to do checks on stage before deploying to production when the code is different. Now you could argue that the same then should apply to OSGi configurations - but there we need to relax a little bit to better support existing projects

**Comment by kwin** [comment]
Thanks, clear now. Would be good to enhance the documentation in https://experienceleague.adobe.com/docs/experience-manager-cloud-service/implementing/developing/aem-project-content-package-structure.html?lang=en#code-packages-%2F-osgi-bundles in that regard.

**Comment by cziegeler** [comment]
@kwin Good point, thanks, I'll get the docs updated
