### ISSUE TITLE
Make version check optional

### ISSUE THREAD

**Issue by geryheselmans** [adobe/aemanalyser-maven-plugin#283]
### Expected Behaviour
A version update of the plugin should only optionally fail the build in strictValidation mode. 

### Actual Behaviour
At a client of mine all builds failed when a new update of the plugin was released, this included release and hotfix build which we want to be reproducible. 

We configured the plugin with strictValidation mode, turning every warning into an error. We want to use strictValidation mode because we also want to check warnings by the plugin. However we don't the build to fail once a new version is available.

Is it possible to add an extra validator setting to specifically disable this functionality? Or some other solution so the build does not automatically fail when a new version is available.

### Reproduce Scenario (including but not limited to)
Configure the project 
```
<plugins>
      <plugin>
          <groupId>com.adobe.aem</groupId>
          <artifactId>aemanalyser-maven-plugin</artifactId>
          <version>1.5.12</version>
          <configuration>
               <strictValidation>true</strictValidation >
          </configuration>
          <executions>
                <execution>
                    <id>aem-analyser</id>
                    <goals>
                        <goal>project-analyse</goal>                           
                    </goals>
                </execution>
            </executions>
      </plugin>
</plugins>
```

#### Steps to Reproduce
n/a

#### Platform and Version
AEM 6.5 On Prem
Mac OS X
non latest version of the plugin

#### Sample Code that illustrates the problem
n/a

#### Logs taken while reproducing problem
n/a

**Comment by cziegeler** [comment]
Thanks for the suggestion; I agree that it makes sense to differentiate between the two.
