### ISSUE TITLE
New check for order of run modes

### ISSUE THREAD

**Issue by kwin** [adobe/aemanalyser-maven-plugin#31]
While OSGi configurations in `/apps/.../config.author.dev` is considered it isn't in `/apps/.../config.dev.author`. A check would be nice which would validate
- the order of run modes
- the run mode values

**Comment by kwin** [comment]
This can be implemented with an analyser as proposed in https://issues.apache.org/jira/browse/SLING-10285, as the run modes end up as classifier in the feature model id (https://github.com/apache/sling-org-apache-sling-feature-cpconverter/blob/8e2eda722d6d4b9d8007711d9bee9ce57ce48a67/src/main/java/org/apache/sling/feature/cpconverter/features/DefaultFeaturesManager.java#L412)

**Comment by kwin** [comment]
The following classifiers are considered by AEMaaCS: 
- author
- author.dev
- author.stage
- author.prod
- publish
- publish.dev
- publish.stage
- publish.prod
- dev
- stage
- prod

Everything else is disregarded.

**Comment by cziegeler** [comment]
I don't think this should be implemented with a feature model analyser. That is a too generic check and we can provide better user feedback with doing the check directly in the plugin

**Comment by cziegeler** [comment]
I suggest we only analyse the above mentioned list and then:

- issue a warning if the run modes are used in the wrong order
- issue an info if other run modes are used

**Comment by kwin** [comment]
In real projects I received tons of warnings, so I never checked those. Therefore I would go as strict as possible.
I.e. `error` for (known) run modes in wrong order.
Using an `info` for other run modes is fine for now, the other alternative is to explicitly configure which other ones should be supported, but that is not-backwards compatible.
