### ISSUE TITLE
Combine work into a single mojo

### ISSUE THREAD

**Issue by cziegeler** [adobe/aemanalyser-maven-plugin#43]
Currently we have three different mojos (converter, aggregator, analyser) - however there is no point in running them separately or allowing any modification in between each step. 
To make it easier to use we should combine the work into a single mojo - this will also reduce some duplicate code and avoids passing information from one mojo to another via project context attributes.
We could make two sub classes of that mojo to be used - one which is by default used with the aemanalyse packaging and the other one which can be used within a content package project.
We should also remove all configuration options from the mojos which are not necessary to create a small configuration surface

**Comment by bosschaert** [comment]
Originally the main reason for having 3 mojos was that they could inherit from existing mojos that did all the work. They basically provided configuration for those existing mojos.
Now that this is refactored and they don't extend those existing mojos any more there is no real reason why we need 3 separate mojos any more...

**Comment by karlpauls** [comment]
👍 - Sounds good to me.

**Comment by cziegeler** [comment]
Resolved by #44
