### ISSUE TITLE
Clarify usage in dedicated module vs usage in existing content packages

### ISSUE THREAD

**Issue by kwin** [adobe/aemanalyser-maven-plugin#46]
Look at https://github.com/adobe/aem-project-archetype/issues/679 for a concrete issue with using a dedicated module. The readme still refers usage of a dedicated package.As it never makes sense to deploy anything for the analysis I would rather recommend always enabling that on an existing content-package module and get rid of the packaging `aem-analyse` (especially as now we have only one Mojo so there is no added value through a lifecycle configuration for a custom packaging)

**Comment by cziegeler** [comment]
Agreed, it is better and easier to just add the plugin to the content package project .
We should deprecate the packaging and usage of the separate module
