### ISSUE TITLE
tmp folder not cleaned up after run

### ISSUE THREAD

**Issue by kwin** [adobe/aemanalyser-maven-plugin#76]
With every execution of `aemanalyser-maven-plugin:project-analyse` in version 1.0.4 there is three new folders below the Java tmp folder generated: one with prefix `cp2fm-converter` and two folders starting with prefix `slingfeature`. All three have a random number after the prefix.
All three together have a substantial size (675MB). Each new build adds another three folders.

Please make sure to cleanup the java tmp folder so that there are no leftovers after the Maven build.

**Comment by kwin** [comment]
Some more information about the contents of those folders:
The ones with prefix `slingfeature` are empty while the ones starting with `cp2fm-converter` have the following subfolders
```
drwxr-xr-x  25 konradwindszus  staff  800 Jun  2 17:45 sub-content-packages
drwxr-xr-x   4 konradwindszus  staff  128 Jun  2 17:45 synthetic-content-packages_1622648734698
drwxr-xr-x   4 konradwindszus  staff  128 Jun  2 17:45 synthetic-content-packages_1622648735284
drwxr-xr-x   4 konradwindszus  staff  128 Jun  2 17:45 synthetic-content-packages_1622648735300
drwxr-xr-x   4 konradwindszus  staff  128 Jun  2 17:45 synthetic-content-packages_1622648735349
drwxr-xr-x   4 konradwindszus  staff  128 Jun  2 17:45 synthetic-content-packages_1622648735523
drwxr-xr-x   4 konradwindszus  staff  128 Jun  2 17:45 synthetic-content-packages_1622648735534
drwxr-xr-x   4 konradwindszus  staff  128 Jun  2 17:45 synthetic-content-packages_1622648737350
drwxr-xr-x   4 konradwindszus  staff  128 Jun  2 17:45 synthetic-content-packages_1622648737522
drwxr-xr-x   4 konradwindszus  staff  128 Jun  2 17:45 synthetic-content-packages_1622648737529
drwxr-xr-x   4 konradwindszus  staff  128 Jun  2 17:45 synthetic-content-packages_1622648737740
drwxr-xr-x   4 konradwindszus  staff  128 Jun  2 17:45 synthetic-content-packages_1622648737815
drwxr-xr-x   4 konradwindszus  staff  128 Jun  2 17:45 synthetic-content-packages_1622648746125
drwxr-xr-x   4 konradwindszus  staff  128 Jun  2 17:45 synthetic-content-packages_1622648746558
drwxr-xr-x   4 konradwindszus  staff  128 Jun  2 17:45 synthetic-content-packages_1622648746600
drwxr-xr-x   4 konradwindszus  staff  128 Jun  2 17:45 synthetic-content-packages_1622648746641
drwxr-xr-x   4 konradwindszus  staff  128 Jun  2 17:45 synthetic-content-packages_1622648746685
drwxr-xr-x   4 konradwindszus  staff  128 Jun  2 17:45 synthetic-content-packages_1622648746715
drwxr-xr-x   4 konradwindszus  staff  128 Jun  2 17:45 synthetic-content-packages_1622648746830
drwxr-xr-x   4 konradwindszus  staff  128 Jun  2 17:45 synthetic-content-packages_1622648746912
drwxr-xr-x   4 konradwindszus  staff  128 Jun  2 17:45 synthetic-content-packages_1622648746940
drwxr-xr-x   4 konradwindszus  staff  128 Jun  2 17:45 synthetic-content-packages_1622648747198
drwxr-xr-x   4 konradwindszus  staff  128 Jun  2 17:45 synthetic-content-packages_1622648747238
drwxr-xr-x   4 konradwindszus  staff  128 Jun  2 17:45 synthetic-content-packages_1622648747384
drwxr-xr-x   4 konradwindszus  staff  128 Jun  2 17:45 synthetic-content-packages_1622648747556
```

**Comment by kwin** [comment]
This is a pretty severe issue with our inhouse CI system, as that quickly runs out of disk space due to this. We had to disable executing the plugin for now. Also the local disk of developers is filling up pretty quickly due to this.

**Comment by kwin** [comment]
Probably the issue is that https://github.com/apache/sling-org-apache-sling-feature-cpconverter/blob/c3ded1a474fd0c8a53d5de055707d6f0a79d6980/src/main/java/org/apache/sling/feature/cpconverter/ContentPackage2FeatureModelConverter.java#L211 is never called in https://github.com/adobe/aemanalyser-maven-plugin/blob/main/aemanalyser-maven-plugin/src/main/java/com/adobe/aem/analyser/AemPackageConverter.java/

**Comment by kwin** [comment]
The empty `slingfeature` folders are generated in `AemAggregator.aggregate` (not during conversion)

**Comment by kwin** [comment]
@bosschaert Would it be possible to release a version containing this fix?

**Comment by bosschaert** [comment]
Sure I'll look into it

**Comment by bosschaert** [comment]
Release done: https://repo1.maven.org/maven2/com/adobe/aem/aemanalyser-maven-plugin/1.0.8/
