### ISSUE TITLE
Create analyser which replicates the logic from CQBP-84

### ISSUE THREAD

**Issue by kwin** [adobe/aemanalyser-maven-plugin#78]
The Sonar rule described in https://experienceleague.adobe.com/docs/experience-manager-cloud-manager/using/how-to-use/custom-code-quality-rules.html?lang=en#product-apis-annotated-with-providertype-should-not-be-implemented-or-extended-by-customers is currently only executed in Cloud Manager.
It would be helpful to check the code for implementation of interfaces marked as "providertype" even locally.

Recently the check has been raised to Critical severity which triggers issues e.g. in 

1. ACS AEM Commons: https://github.com/Adobe-Consulting-Services/acs-aem-commons/issues/2604
2. ACTool: https://github.com/Netcentric/accesscontroltool/issues/584
3. AEM Easy Content Upgrade (AECU): https://github.com/valtech/aem-easy-content-upgrade/issues/156

**Comment by kwin** [comment]
I opened https://issues.apache.org/jira/browse/SLING-12026 for the implementation of the according Feature Model Analyser.

**Comment by dporter-moveworks** [comment]
Closed #2587 after updating WCM 2.32.2 -> 2.23.4

**Comment by kwin** [comment]
This is supported with the bnd plugin provided at https://github.com/apache/sling-org-apache-sling-providertype-bnd-plugin. Outside the scope of the aemanalyser.
