### ISSUE TITLE
Create analyser which fails when OSGi configurations/bundles are outside expected locations

### ISSUE THREAD

**Issue by kwin** [adobe/aemanalyser-maven-plugin#80]
Although the package `com.composum.nodes:composum-nodes-aem-package:2.6.5` is a perfectly valid AEM package, it cannot be deployed to AEMaaCS.

Its inclusion in a container package leads to the following error in `cp2fm` executed by Cloud Manager:

```
[0m[91m[INFO] Apache Sling Content Package to Sling Feature converter FAILURE[0m[91m
[0m[91m[INFO] +-----------------------------------------------------+[0m[91m
[0m[91m[ERROR] Unable to convert content-package [/tmp/packages/my-container-package-1.0.0-SNAPSHOT.zip]: OSGi configuration are only considered if placed below a folder called 'config', but the configuration at '/jcr_root/libs/composum/nodes/install/org.apache.sling.jcr.base.internal.LoginAdminWhitelist.fragment-composum_core_v2.config' is placed outside![0m[91m
[0m[91m[INFO] +-----------------------------------------------------+
[0m[91m[INFO] Total time: 9 seconds
[0m[91m[INFO] Finished at: Mon Jul 12 16:27:39 UTC 2021[0m[91m
[0m[91m[INFO] Final Memory: 54M/132M[0m[91m
[0m[91m[INFO] +-----------------------------------------------------+[0m[91m
[0mThe command '/bin/sh -c CP2SF_BINARY="/tmp/cpconverter/bin/cp2fm" ./preparePackages.sh src/main/features src/main/docker/container/root/opt/aem/content-refs/packages.csv $failonMixedPackage $packageLocations' returned a non-zero code: 1
2021/07/12 16:27:40 Container failed during run: build-image. No retries remaining.
failed to run step ID: build-image: exit status 1

Run ID: caeywd failed after 2m47s. Error: failed during run, err: exit status 1
```

This is due to the fact, that cp2fm as configured in AEMaaCS does not support configurations below `install` (https://issues.apache.org/jira/browse/SLING-10278). Such errors should be detected by aemanalyser-maven-plugin already.

**Comment by cziegeler** [comment]
@kwin Is my understanding correct that the aemanalyser plugin happily converts that package without an error? If that's the case we probably have a mismatch in running the converter in this plugin and in the Cloud Manager pipeline - which we should fix in the aemanalyser plugin.

**Comment by kwin** [comment]
bq.  Is my understanding correct that the aemanalyser plugin happily converts that package without an error?

Yes, aemanalyser does not fail, only Cloud Manager does!
