### ISSUE TITLE
Make it possible to run the AEM Analyser outside of Maven as a standalone tool

### ISSUE THREAD

**Issue by bosschaert** [adobe/aemanalyser-maven-plugin#81]
Right now the AEM Analyser is implemented as a Maven Plugin.

However we need to run the Analyser in scenarios where Maven is not present. For this a standalone tool that executes the AEM Analyser is needed.

**Comment by kwin** [comment]
Could you shed some light on why this has been removed again @bosschaert?

**Comment by bosschaert** [comment]
@kwin the tool that was there was just a thin starting point, and it wasn't really ready to be used widely, so I removed it temporarily.
