### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by bosschaert** [adobe/aemanalyser-maven-plugin#83]
Now that this repository contains more than just the Maven plugin (it also contains a command-line tool) we should rename the repository to be more generic. For example we could just rename it to: `aemanalyser`.

**Comment by raducotescu** [comment]
Could you rename the repo and artifacts to `aem-*`, given that you haven't released anything yet?

**Comment by bosschaert** [comment]
the aemanalyser-maven-plugin has already been released multiple times: https://repo1.maven.org/maven2/com/adobe/aem/aemanalyser-maven-plugin/

**Comment by raducotescu** [comment]
Sorry, I didn't see the tags... :(

**Comment by cziegeler** [comment]
@bosschaert I think we should either rename to "aemanalyser" as you suggest or just close this issue. Either is fine with me.

**Comment by bosschaert** [comment]
I think this is not so important right now, so let's close the issue. We can always reopen it if the need arises.
