### ISSUE TITLE
Errors/Warnings should emit the responsible task.

### ISSUE THREAD

**Issue by kwin** [adobe/aemanalyser-maven-plugin#88]
The logs from individual tasks should be prefixed with the task name, so that it easier to disable the task via https://github.com/adobe/aemanalyser-maven-plugin/tree/main/aemanalyser-maven-plugin#selecting-tasks

**Comment by cziegeler** [comment]
I'm not really a fan of disabling tasks - these are the tasks that are execute by Cloud Manager - so disabling a task will result in a failure in Cloud Manager regardless

**Comment by kwin** [comment]
This is not only useful to disable the task but also to get a better understanding of the underlying issue, so each log message from an analyser task should be prefixed. Some log messages really make it difficult to associate them with a concrete task.

**Comment by cziegeler** [comment]
ok, this needs to be implemented in Apache Sling's feature analyser.

**Comment by cziegeler** [comment]
https://issues.apache.org/jira/browse/SLING-10708

**Comment by cziegeler** [comment]
Added with https://github.com/adobe/aemanalyser-maven-plugin/commit/2e07c8fe9e945f5955fa13c573f6cee115e11fd5
