### ISSUE TITLE
AEM Analyser Plugin v1.1.2 has internal dependencies that cannot be resolved (follow-up to issue 91)

### ISSUE THREAD

**Issue by pahupe** [adobe/aemanalyser-maven-plugin#93]
### Expected Behaviour

Context: AEM as a Cloud maven project workspace
When bumping up the AEM Analyser Plugin version to 1.1.2, the plugin will execute and analyse the workspace artifacts

### Actual Behaviour
The plugin version 1.1.2 apparently has "internal dependencies" which cannot be downloaded from outside Adobe, which causes the plugin to fail

#### Steps to Reproduce

In the root pom.xml, set the plugin version to 1.1.2:

<aemanalyser.version>1.1.2</aemanalyser.version>

In the "all" module, run the plugin with goal "project-analyse"

            <plugin>
                <groupId>com.adobe.aem</groupId>
                <artifactId>aemanalyser-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>aem-analyser</id>
                        <goals>
                            <goal>project-analyse</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

Make sure to not override any plugin dependencies in the root pom.xml

        
        <plugin>
          <groupId>com.adobe.aem</groupId>
          <artifactId>aemanalyser-maven-plugin</artifactId>
          <version>${aemanalyser.version}</version>
          <extensions>true</extensions>
        </plugin>

#### Platform and Version

<aem.sdk.api>2021.6.5561.20210622T143945Z-210600</aem.sdk.api> but shouldn't really matter
AEM as as Cloud project based on archetype v28

#### Sample Code that illustrates the problem

(see above)

#### Logs taken while reproducing problem

[INFO] --- aemanalyser-maven-plugin:1.1.2:project-analyse (aem-analyser) @ customername.all ---
[INFO] artifact com.adobe.aem:aem-sdk-api: checking for updates from adobe-public-releases
[INFO] artifact com.adobe.aem:aem-sdk-api: checking for updates from central
[INFO] Using detected SDK Version for analysis: com.adobe.aem:aem-sdk-api:2021.8.5705.20210810T082946Z-210700

...

[INFO] Building aggregate feature model aggregated-author.prod...
[INFO] Building aggregate feature model aggregated-author.dev...
[INFO] Building aggregate feature model aggregated-publish.prod...
[INFO] Building aggregate feature model aggregated-publish.stage...
[INFO] Building aggregate feature model aggregated-author.stage...
[INFO] Building aggregate feature model aggregated-publish.dev...
[INFO] Starting analyzing feature 'com.example:customername.all:slingosgifeature:aggregated-author.prod:1.0.0-SNAPSHOT'...

Downloading from adobe-public-releases: http://repo.adobe.com/nexus/content/groups/public/org/apache/sling/org.apache.sling.metrics.osgi.collector/0.1.0-T20200317112827-d4c51d6/org.apache.sling.metrics.osgi.collector-0.1.0-T20200317112827-d4c51d6.jar

Downloading from central: https://repo.maven.apache.org/maven2/org/apache/sling/org.apache.sling.metrics.osgi.collector/0.1.0-T20200317112827-d4c51d6/org.apache.sling.metrics.osgi.collector-0.1.0-T20200317112827-d4c51d6.jar

(these downloads fail)

**Comment by pahupe** [comment]
### Known workaround ###

Keep the aemanalyser plugin version at 1.0.x (here: 1.0.10) and pin the johnzon dependency version to 1.2.14:

In root pom.xml:

...

        <aemanalyser.version>1.0.10</aemanalyser.version>

...

                
                <plugin>
                    <groupId>com.adobe.aem</groupId>
                    <artifactId>aemanalyser-maven-plugin</artifactId>
                    <version>${aemanalyser.version}</version>
                    <extensions>true</extensions>
                    <dependencies>
                        <dependency>
                            <groupId>org.apache.johnzon</groupId>
                            <artifactId>johnzon-core</artifactId>
                            <version>1.2.14</version>
                        </dependency>
                    </dependencies>
                </plugin>

**Comment by cziegeler** [comment]
https://issues.apache.org/jira/browse/SLING-10729

**Comment by cziegeler** [comment]
Fixed with https://github.com/adobe/aemanalyser-maven-plugin/commit/2e07c8fe9e945f5955fa13c573f6cee115e11fd5
