### ISSUE TITLE
RepoInit 'delete' command rejected by analyser plugin v1.1.4

### ISSUE THREAD

**Issue by pahupe** [adobe/aemanalyser-maven-plugin#99]
### Expected Behaviour

RepoInit scripts containing the command 'delete' are accepted, since the delete command now exists for a while (ref:  https://sling.apache.org/documentation/bundles/repository-initialization.html) and the aem analyser plugin version is quite new

### Actual Behaviour

The aem analyser plugin reports an error when parsing the delete command (see example below)

### Reproduce Scenario (including but not limited to)

AEM SDK (local) v5662 (but also tested with 5755)

AEM analyser plugin v1.1.4 

```
[INFO] --- aemanalyser-maven-plugin:1.1.4:project-analyse (aem-analyser) @ myapp.all ---
[INFO] artifact com.adobe.aem:aemanalyser-maven-plugin: checking for updates from adobe-public-releases
[INFO] artifact com.adobe.aem:aemanalyser-maven-plugin: checking for updates from central
[INFO] artifact com.adobe.aem:aem-sdk-api: checking for updates from adobe-public-releases
[INFO] artifact com.adobe.aem:aem-sdk-api: checking for updates from central
[INFO] Using detected SDK Version for analysis: com.adobe.aem:aem-sdk-api:2021.8.5755.20210819T230729Z-210700
...
```

1. root pom.xml:

```
    <aemanalyser.version>1.1.4</aemanalyser.version>
```
    
2. all/pom.xml:

```
            <plugin>
                <groupId>com.adobe.aem</groupId>
                <artifactId>aemanalyser-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>aem-analyser</id>
                        <goals>
                            <goal>project-analyse</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

3. repoinit script (org.apache.sling.jcr.repoinit.RepositoryInitializer~customerservice.config):

```
# move service user home directory (force path), create principal-based ACLs, delete existing resource-based ACLs
scripts=["
create service user customer-service with forced path system/cq:services/customer
set principal ACL for customer-service
  allow jcr:read on /content/myapp/de/de,/content/dam
end
delete ACL for customer-service
"]
```

4. Analyser error:

Local run:
```
[ERROR] The analyser found the following errors for author and publish :
[ERROR] [repoinit] repoinit: Parsing error in repoinit from extension : Encountered " "delete" "delete "" at line 5, column 1.
Was expecting:
    <EOF>
```

#### Steps to Reproduce

see above

#### Platform and Version

Mac OS 11.5.2, local build, Java 11

Tested with AEM SDK 5662 and AEM SDK 5755

#### Sample Code that illustrates the problem

see above

#### Logs taken while reproducing problem

see above

**Comment by karlpauls** [comment]
Should be fixed by https://github.com/adobe/aemanalyser-maven-plugin/commit/380d918435fd20f77eef233d8d4ce33a26a267a4 which is in the new 1.1.6 release
